RunGroopWebAppp/Models/Address.cs
using System.ComponentModel.DataAnnotations;

namespace RunGroopWebApp.Models
{
    public class Address
    {

        [Key]

        public int Id { get; set; }

        public string Street { get; set; }

        public string City { get; set; }

        public string State { get; set; }

    }
}

RunGroopWebAppp/Models/AppUser.cs
using Microsoft.AspNetCore.Identity;
using RunGroopWebAppp.Models;

namespace RunGroopWebApp.Models
{
    public class AppUser : IdentityUser
    {

        public Address? Address { get; set; }

        public int? pace { get; set; }

        public int? Mileage { get; set; }

        public ICollection<Club> Clubs { get; set; }

        public ICollection<Race> Races { get; set; }



    }
}

RunGroopWebAppp/Models/Club.cs
using RunGroopWebApp.Data.Enum;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace RunGroopWebApp.Models
{
    public class Club
    {

        [Key]

        public int Id { get; set; }

        public string Title { get; set; }

        public string Description { get; set; }

        public string Image { get; set; }

        [ForeignKey("Address")]

        public int AddressId { get; set; }

        public Address Address { get; set; }

        public ClubCategory ClubCategory { get; set; }

        [ForeignKey("AppUser")]

        public string? AppUserId { get; set; }

        public AppUser? AppUser { get; set; }




    }
}

RunGroopWebAppp/Models/ErrorViewModel.cs
namespace RunGroopWebAppp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

RunGroopWebAppp/Models/Race.cs
using RunGroopWebApp.Data.Enum;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace RunGroopWebApp.Models
{
    public class Race
    {

        [Key]

        public int Id { get; set; }

        public string Tittle { get; set; }

        public string Description { get; set; }

        public string Image { get; set; }

        [ForeignKey("Address")]

        public int AddressId { get; set; }

        public Address Address { get; set; }

        public RaceCategory RaceCategory { get; set; }

        [ForeignKey("AppUser")]

        public string? AppUserId { get; set; }

        public AppUser? AppUser { get; set; }
        public string Title { get; internal set; }
    }
}

RunGroopWebAppp/ViewModels/CreateClubViewModel.cs
using RunGroopWebApp.Data.Enum;
using RunGroopWebApp.Models;

namespace RunGroopWebAppp.ViewModels
{
    public class CreateClubViewModel
    {

        //public string Tittle { get; set; }

        public int Id { get; set; }

        public string Tittle { get; set; }

        public string Description { get; set; }

        public Address Address { get; set; }

        public IFormFile Image { get; set; }

        public ClubCategory ClubCategory { get; set; }
        public string Title { get; internal set; }
    }
}

RunGroopWebAppp/ViewModels/CreateRaceViewModel.cs
using RunGroopWebApp.Data.Enum;
using RunGroopWebApp.Models;

namespace RunGroopWebAppp.ViewModels
{
    public class CreateRaceViewModel
    {

        public int Id { get; set; }

        public string Tittle { get; set; }

        public string Description { get; set; }

        public Address Address { get; set; }

        public IFormFile Image { get; set; }

        public RaceCategory RaceCategory { get; set; }
        public string Title { get; internal set; }
    }
}

RunGroopWebAppp/Controllers/ClubController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RunGroopWebApp.Data;
using RunGroopWebApp.Models;
using RunGroopWebAppp.Interfaces;
using RunGroopWebAppp.ViewModels;

namespace RunGroopWebAppp.Controllers
{
    public class ClubController : Controller
    {


        private readonly IClubRepository _clubRepository;
        private readonly IPhotoServices _photoServices;
        public ClubController( IClubRepository clubRepository , IPhotoServices photoServices)
        {

            _clubRepository = clubRepository;
            _photoServices = photoServices;
           
            
        }
        public async Task<IActionResult> Index()
        {
            IEnumerable<Club> clubs =await _clubRepository.GetAll();
            return View(clubs);
        }

        public async Task<IActionResult> Detail(int id)

        {

            Club club = await _clubRepository.GetByIdAsync(id);
            return View(club);


        }

        public IActionResult Create()
        {

            return View();
        }

        [HttpPost]

        public async Task<IActionResult> Create(CreateClubViewModel clubVM)

        {

            if(ModelState.IsValid)
            {
                var result = await _photoServices.AddPhotoAsync(clubVM.Image);

                var club = new Club
                {
                    Title = clubVM.Title,
                    Description = clubVM.Description,
                    Image = result.Url.ToString(),
                    Address = new Address
                    {
                        City = clubVM.Address.City,
                        Street = clubVM.Address.Street,
                        State = clubVM.Address.State,
                    }
                };

             _clubRepository.Add(club);
             return RedirectToAction("Index");

            
           }

            else

            {

                ModelState.AddModelError("", "Please fill all the fields");
            }

            return View(clubVM);
           
        }
          
    }
}

RunGroopWebAppp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using RunGroopWebAppp.Models;
using System.Diagnostics;

namespace RunGroopWebAppp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

RunGroopWebAppp/Controllers/RaceController.cs
using Microsoft.AspNetCore.Mvc;
using RunGroopWebApp.Data;
using RunGroopWebApp.Models;
using RunGroopWebAppp.Interfaces;
using RunGroopWebAppp.Repository;
using RunGroopWebAppp.Services;
using RunGroopWebAppp.ViewModels;

namespace RunGroopWebAppp.Controllers
{
    public class RaceController : Controller
    {

        private readonly IRaceRepository _raceRepository;
        private readonly IPhotoServices _photoServices;

        public RaceController( IRaceRepository raceRepository , IPhotoServices photoServices)
        {

            _raceRepository = raceRepository;
            _photoServices = photoServices;

        }
        public async Task<IActionResult> Index()
        {
            IEnumerable<Race> races = await _raceRepository.GetAll();
            return View(races);
        }

        public async Task<IActionResult> Detail(int id)

        {
            Race race = await _raceRepository.GetByIdAsync(id);
            return View(race);
        }

        public IActionResult Create()
        {

            return View();
        }

        [HttpPost]

        public async Task<IActionResult> Create(CreateRaceViewModel raceVN)

        {

            if (ModelState.IsValid)
            {
                var result = await _photoServices.AddPhotoAsync(raceVN.Image);

                var race = new Race
                {
                    Title = raceVN.Title,
                    Description = raceVN.Description,
                    Image = result.Url.ToString(),
                    Address = new Address
                    {
                        City = raceVN.Address.City,
                        Street = raceVN.Address.Street,
                        State = raceVN.Address.State,
                    }
                };

                _raceRepository.Add(race);
                return RedirectToAction("Index");


            }

            else

            {

                ModelState.AddModelError("", "Please fill all the fields");
            }

            return View(raceVN);

        }

    }
}

RunGroopWebAppp/Views/Club/Create.cshtml
@using RunGroopWebApp.Data.Enum
@model RunGroopWebAppp.Models.Club
@using RunGroopWebAppp.ViewModels
@model CreateClubViewModel


@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


<form method="post" asp-action="Create" enctype="multipart/form-data">
    <input type="hidden" id="AppUserId" name="AppUserId" asp-for="AppUserId" />
    <div class="form-row form-group">
        <div class="col">
            <input asp-for="Title" class="form-control form-control-lg" placeholder="Title" />
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
        <div class="col">
            <select asp-for="ClubCategory" asp-items="@Html.GetEnumSelectList<ClubCategory>()" class="form-control form-control-lg">
                <option>--Select--</option>
            </select>
            <span asp-validation-for="ClubCategory" class="text-danger"></span>
        </div>
    </div>
    <div class="form-row form-group">
        <div class="col">
            <input asp-for="Description" class="form-control form-control-lg" placeholder="Description" />
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
    </div>
    <div class="form-row form-group">
        <div class="col">
            <input asp-for="Address.Street" class="form-control form-control-lg" placeholder="Street" />
            <span asp-validation-for="Address.Street" class="text-danger"></span>
        </div>
    </div>
    <div class="form-row form-group">
        <div class="col">
            <input asp-for="Address.City" class="form-control form-control-lg" placeholder="City" />
            <span asp-validation-for="Address.City" class="text-danger"></span>
        </div>
        <div class="col">
            <input asp-for="Address.State" class="form-control form-control-lg" placeholder="State" />
            <span asp-validation-for="Address.State" class="text-danger"></span>
        </div>
    </div>
    <div class="form-row form-group">
        <div class="col">
            <input asp-for="Image" type="file" class="form-control form-control-lg" placeholder="Image" />
            <span asp-validation-for="Image" class="text-danger"></span>
        </div>
    </div>
    <div class="form-row form-group">
        <div class="col">
            <button class="btn btn-block btn-success btn-lg" type="submit">Create Account</button>
        </div>
    </div>
</form>
                </div>
              </div>
            </div>
          </div>
        </div>
<!--end of container-->
      </section>
<!--end of section-->
    </div>

RunGroopWebAppp/Views/Club/Detail.cshtml
@model RunGroopWebAppp.Models.Club
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<!-- Page Content -->
<div class="container">

    <!-- Portfolio Item Heading -->
    <h1 class="my-4">
        Page Heading
        <small>Secondary Text</small>
    </h1>

    <!-- Portfolio Item Row -->
    <div class="row">

        <div class="col-md-8">
            <img class="img-fluid" src="@Model.Image" alt="">
        </div>

        <div class="col-md-4">
            <h3 class="my-3">@Model.Title</h3>
            <p>@Model.Description</p>
            <h3 class="my-3">Location</h3>
            <ul>
                <li>@Model.Address.City</li>
                <li>@Model.Address.State</li>
                <li>@Model.ClubCategory</li>
            </ul>
        </div>

    </div>
    <!-- /.row -->
    <!-- Related Projects Row -->
    <h3 class="my-4">Related Projects</h3>

    <div class="row">

        <div class="col-md-3 col-sm-6 mb-4">
            <a href="#">
                <img class="img-fluid" src="https://via.placeholder.com/500x300" alt="">
            </a>
        </div>

        <div class="col-md-3 col-sm-6 mb-4">
            <a href="#">
                <img class="img-fluid" src="https://via.placeholder.com/500x300" alt="">
            </a>
        </div>

        <div class="col-md-3 col-sm-6 mb-4">
            <a href="#">
                <img class="img-fluid" src="https://via.placeholder.com/500x300" alt="">
            </a>
        </div>

        <div class="col-md-3 col-sm-6 mb-4">
            <a href="#">
                <img class="img-fluid" src="https://via.placeholder.com/500x300" alt="">
            </a>
        </div>

    </div>
    <!-- /.row -->

</div>
<!-- /.container -->

RunGroopWebAppp/Views/Club/Index.cshtml
@model IEnumerable<RunGroopWebApp.Models.Club>
@{
    ViewData["Title"] = "Clubs";
}

<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            @foreach (var item in Model)
            {
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <img class="card-img-top" src="@item.Image" style="width: 100%; height: 225px;" alt="Card image cap">
                        <div class="card-body">
                            <p class="card-text">@item.Title</p>
                            <p class="card-text">@item.Description</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a asp-controller="Club" asp-action="Detail" asp-route-id="@item.Id" class="btn btn-sm btn-outline-secondary">View</a>
                                    <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                                </div>
                                <small class="text-muted">@item.ClubCategory</small>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

RunGroopWebAppp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading">RunGroops</h1>
        <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don't simply skip over it entirely.</p>
        <p>
            <a href="#" class="btn btn-primary my-2">Main call to action</a>
            <a href="#" class="btn btn-secondary my-2">Secondary action</a>
        </p>
    </div>
</section>
<div class="album py-5 bg-light">
    <div class="container">

        <div class="row">
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&bg=55595c&fg=eceeef&text=Thumbnail" alt="Card image cap">
                    <div class="card-body">
                        <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                                <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                            </div>
                            <small class="text-muted">9 mins</small>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&bg=55595c&fg=eceeef&text=Thumbnail" alt="Card image cap">
                    <div class="card-body">
                        <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                                <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                            </div>
                            <small class="text-muted">9 mins</small>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&bg=55595c&fg=eceeef&text=Thumbnail" alt="Card image cap">
                    <div class="card-body">
                        <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                                <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                            </div>
                            <small class="text-muted">9 mins</small>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&bg=55595c&fg=eceeef&text=Thumbnail" alt="Card image cap">
                    <div class="card-body">
                        <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                                <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                            </div>
                            <small class="text-muted">9 mins</small>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&bg=55595c&fg=eceeef&text=Thumbnail" alt="Card image cap">
                    <div class="card-body">
                        <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                                <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                            </div>
                            <small class="text-muted">9 mins</small>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&bg=55595c&fg=eceeef&text=Thumbnail" alt="Card image cap">
                    <div class="card-body">
                        <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                                <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                            </div>
                            <small class="text-muted">9 mins</small>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&bg=55595c&fg=eceeef&text=Thumbnail" alt="Card image cap">
                    <div class="card-body">
                        <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                                <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                            </div>
                            <small class="text-muted">9 mins</small>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&bg=55595c&fg=eceeef&text=Thumbnail" alt="Card image cap">
                    <div class="card-body">
                        <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                                <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                            </div>
                            <small class="text-muted">9 mins</small>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&bg=55595c&fg=eceeef&text=Thumbnail" alt="Card image cap">
                    <div class="card-body">
                        <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                                <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                            </div>
                            <small class="text-muted">9 mins</small>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

RunGroopWebAppp/Views/Race/Create.cshtml
@model RunGroopWebApp.Models.Race
@model CreateRaceViewModel
@using RunGroopWebApp.Data.Enum
@using RunGroopWebAppp.ViewModels

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}




<form method="post" asp-action="Create" enctype="multipart/form-data">
    <input type="hidden" id="AppUserId" name="AppUserId" asp-for="AppUserId" />
    <div class="form-group">
        <label asp-for="Title">Title</label>
        <input asp-for="Title" class="form-control" placeholder="Title">
        <span asp-validation-for="Title" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Description">Description</label>
        <input asp-for="Description" class="form-control" placeholder="Description">
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="RaceCategory">Race Category</label>
        <select asp-for="RaceCategory" asp-items="@Html.GetEnumSelectList<RaceCategory>()" class="form-control">
            <option>--Select--</option>
        </select>
        <span asp-validation-for="RaceCategory" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Address.Street">Street</label>
        <input asp-for="Address.Street" class="form-control" placeholder="Street">
        <span asp-validation-for="Address.Street" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Address.City">City</label>
        <input asp-for="Address.City" class="form-control" placeholder="Street">
        <span asp-validation-for="Address.Street" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Address.State">State</label>
        <input asp-for="Address.State" class="form-control" placeholder="Street">
        <span asp-validation-for="Address.State" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Image">Image</label>
        <input asp-for="Image" type="file" class="form-control" placeholder="Image">
        <span asp-validation-for="Image" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

RunGroopWebAppp/Views/Race/Index.cshtml
@model RunGroopWebApp.Models.Race
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            @foreach (var item in Model)

            {
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <img class="card-img-top" src="@item.Image" width="100%" height="225" alt="Card image cap">
                        <div class="card-body">
                            <p class="card-text">@item.Tittle</p>
                            <p class="card-text">@item.Description</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a asp-controller="Club" asp-action="Detail" asp-route-id="@item.Id" type="button" class="btn btn-sm btn-outline-secondary">View</a>
                                    <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                                </div>
                                <small class="text-muted">@item.RaceCategory</small>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

RunGroopWebAppp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RunGroopWebAppp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RunGroopWebAppp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RunGroopWebAppp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Club" asp-action="Index">Club</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Races" asp-action="Index">Races</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - RunGroopWebAppp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>